Lombok plugin removed (due to error plugin not found).
After plugin removed everything still works correctly
ERROR: Plugin 'org.springframework.boot:spring-boot-maven-plugin:' not found

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>